language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install ."

# command to run tests
script: |
    mkdir ~/.newslynx/ && \
    wget https://github.com/newslynx/newslynx-core/blob/master/newslynx/dot_newslynx/config.yaml \
        -o ~/.newslynx/config.yaml && \ 
    nosetests